config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: 'homes#top'
  resources :post_gyms  do
  resource :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post_gym
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :post_gym

end

app/models/post_gym.rb
class PostGym < ApplicationRecord
 belongs_to :user
 attachment :image
 has_many :comments, dependent: :destroy
 has_many :likes, dependent: :destroy


  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :post_gyms, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

   attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authenticate_user!,except: [:top]

    before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    post_gyms_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :old, :height, :body_weight, :experience, :profile_image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    post_gym = PostGym.find(params[:post_gym_id])
    comment = current_user.comments.new(comment_params)
    comment.post_gym_id = post_gym.id
    comment.save
    redirect_to post_gym_path(post_gym)
  end


  def destroy
   Comment.find_by(id: params[:id]).destroy
   redirect_to post_gym_path(params[:post_gym_id])
  end

private

def comment_params
  params.require(:comment).permit(:comment)

end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  def create
  post_gym = PostGym.find(params[:post_gym_id])
  like = current_user.likes.new(post_gym_id: post_gym.id)
  like.save
  redirect_to post_gym_path(post_gym)
  end

  def destroy
    post_gym = PostGym.find(params[:post_gym_id])
    like = current_user.likes.find_by(post_gym_id: post_gym.id)
    like.destroy
    redirect_to post_gym_path(post_gym)


  end

end

app/controllers/post_gyms_controller.rb
class PostGymsController < ApplicationController

  def new
    @post_gym = PostGym.new
  end

  def create
  @post_gym = PostGym.new(post_gym_params)
  @post_gym.user_id = current_user.id
  @post_gym.save
  redirect_to post_gyms_path

  end

  def index
  @post_gyms = PostGym.page(params[:page]).reverse_order
  end

  def show
  @post_gym = PostGym.find(params[:id])
  @comment = Comment.new
  end


  def update
  post_gym = PostGym.find(params[:id])
  post_gym.update(post_gym_params)
  redirect_to post_gyms_path(post_gym)
  end

  def edit
  @post_gym = PostGym.find(params[:id])
  end


  def destroy
  @post_gym = PostGym.find(params[:id])
  @post_gym.destroy
  redirect_to post_gyms_path
  end



  private

  def post_gym_params
  params.require(:post_gym).permit(:image, :workout_at, :workout_menu, :aim)

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
   @user = User.find(params[:id])
   @post_gyms = @user.post_gyms.page(params[:page]).reverse_order
  end


  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :old, :height, :body_weight, :experience)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_gyms_helper.rb
module PostGymsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class= "container bg-lights">
    <div class="col-lg-12 mt-3">
      <h2 class="text-center">理想の身体を手に入れろ！！！</h2>
       <div class="text-center"><%= image_tag 'img/m.jpg', size: '600x400', class: "mt-3" %></div>

  <p class="text-center mt-3">筋力トレーニングにおいて大きく分けて二通りのトレーニング方法があります</p>
  <p class="text-center">一つはフィットネスジム(マシーンや器具等が施設に用意されている場所)で行うトレーニング法</p>
  <p class="text-center">、自宅にいながら行えるなど場所にとらわれず何処でも行える自重トレーニングの二通りです。</p>
  <p class="text-center">行なったトレーニングメニューと、そのトレーニングをした目的をこのサイトでシェアしましょう！！！！</p>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workout</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('img/1.jpg') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item  bg-info ml-3">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item  bg-primary ml-3">
              <%= link_to 'Post', new_post_gym_path, class: 'nav-link text-dark' %>
            </li>

            <li class="nav-item bg-success ml-3">
              <%= link_to 'My page', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item bg-dark">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item bg-dark ml-3">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-white' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>

    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-12">
            <strong><p class="text-center">NO Pain No Gain</p></strong>
          </div>

        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_gyms/edit.html.erb
<div class="container mt-4">
<div calss="col-12">
<h3>編集画面</h3>
</div>
</div>

		<%= form_with model: @post_gym, local:true do |f| %>


<div class= "container bg-light mt-3 mb-3">
  <div class= "col-12">
		<table>
			<thead>
				<tr>
				  <th class="col-lg-2 text-center border">today's best photo</th>
				   <td class="col-lg-2"><%= f.attachment_field :image %></td>
         </tr>

	            <tr>
				    <th class="col-lg-2 text-center border ml-2">トレーニング場所</th>
				  	<td class="col-lg-2"><%= f.text_field :workout_at %></td>
                </tr>

                 <tr>
					 <th class="col-lg-4 text-center border">トレーニングメニュー</th>
					 <td class="col-lg-8"><%= f.text_area :workout_menu, :size=>"60x10" %></td>
			    </tr>


					  <tr>
				       <th class="col-lg-4 text-center border">トレーニング説明</th>
				   	   <td class="col-lg-8"> <%= f.text_area :aim, :size=>"60x10" %> </td>
				   	</tr>

				  <tr>
				  <th></th>
				  <div class="text-center">
					<td><%= f.submit '変更を保存', class: "btn btn-primary ml-5" %></td>
					<% end %>
					</div>

				</tr>
			</thead>

  </div>
</div>

			</tbody>
	　</table>

app/views/post_gyms/index.html.erb
<div class="card-list-container py-4">
<% @post_gyms.each do |post_gym| %>

<div class="card w-50 mx-auto mt-3 shadow-lg">

  <div class="card-body">
  <div class="row">
  <div class="col-12">
  <%= attachment_image_tag post_gym.user, :profile_image, :fill, 100, 100,  class:"mt-3 rounded-circle"; %>
   <%= link_to post_gym_path(post_gym.id) do %>
  <p class="text-left mt-3 ml-4"><strong><%= post_gym.user.name %></strong></p>
  <% end %>
  </div>
  </div>
  </div>



<strong>today's best photo</strong>
  <p class="border border"><%= attachment_image_tag post_gym, :image, class:"card-img-top"; %></p>


 <div class="col-12">
　 <p class="card-title">
　    <strong><p class="card-title border" >トレーニング場所: </strong><%= post_gym.workout_at %></strong></p>

     <div class="d-flex flex-row bd-highlight mb-3">
        <strong><p class="col-6 p-2 bd-highlight border card-title">トレーニングメニュー：</strong><br><%= safe_join(post_gym.workout_menu.split("\n"),tag(:br)) %></p>
        <strong><p class="col-6 p-2 bd-highlight border card-title">説明： </strong><br><%= safe_join(post_gym.aim.split("\n"),tag(:br)) %></p>
     </div>
　  <span><i class="fas fa-user"></i> By <%= post_gym.user.name %> ｜ </span>
 <span><%= link_to "#{post_gym.comments.count} コメント", post_gym_path(post_gym.id), class:"text-dark" %></span>

 　　　　</div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate @post_gyms %>
</div>
</div>

app/views/post_gyms/new.html.erb
<div class="container mt-4">
<div calss="col-12">
<h3>Post</h3>
</div>
</div>

<%= form_with model: @post_gym, url: post_gyms_path, local:true do |f| %>

<div class= "container bg-light mt-3 mb-3">
  <div class= "col-12">
		<table>
			<thead>
				<tr>
				<th class="col-lg-2 text-center border">today's best photo</th>
				   <td class="col-lg-2"><%= f.attachment_field :image %></td>
                </tr>

	            <tr>
				    <th class="col-lg-2 text-center border ml-2">トレーニング場所</th>
				  	<td class="col-lg-2"><%= f.text_field :workout_at %></td>
                </tr>

                 <tr>
					 <th class="col-lg-4 text-center border">トレーニングメニュー</th>
					 <td class="col-lg-8"><%= f.text_area :workout_menu, :size=>"60x10" %></td>
			    </tr>


					  <tr>
				       <th class="col-lg-4 text-center border">トレーニング説明</th>
				   	   <td class="col-lg-8"> <%= f.text_area :aim, :size=>"60x10" %> </td>
				   	</tr>

				  <tr>
				  <th></th>
				  <div class="text-center">
					<td><%= f.submit '投稿', class: "btn btn-primary ml-5" %></td>
						<% end %>
					</div>
				</tr>
			</thead>
  </div>
</div>

			</tbody>
	　</table>

app/views/post_gyms/show.html.erb
<div class="post-detail py-5 bg-light">
  <div class="card w-75 mx-auto mt-4 shadow-lg">


<div class="card-body">
      <div class="row">
        <div class="col-7">
          <strong><p class="text-left"><%= attachment_image_tag @post_gym.user, :profile_image, :fill, 60, 60, fallback: "img/1.jpg", class:"mt-3 border border rounded-circle"; %></strong>
        </div>

    <%= attachment_image_tag @post_gym, :image, class:"border card-img-top"; %>
     </div>


 <div class="col-12">

        <strong><p class="p-2  border card-title" >トレーニング場所: </strong><%= @post_gym.workout_at %></strong></p>
       <div class="d-flex flex-row bd-highlight mb-3">
           <strong><p class="col-6 p-2 bd-highlight border card-title">トレーニングメニュー：</strong><br><%= safe_join(@post_gym.workout_menu.split("\n"),tag(:br)) %></p>
           <strong><p class="col-6 p-2 bd-highlight border card-title">説明： </strong><%= safe_join(@post_gym.aim.split("\n"),tag(:br)) %></p>
        </div>
          <span><i class="fas fa-user"></i> By <%= @post_gym.user.name %> ｜ </span>
          <span><i class="fa fa-calendar"></i> <%= @post_gym.created_at.strftime('%Y/%m/%d') %> ｜ </span>

          <% if @post_gym.liked_by?(current_user) %>
            <span>
              <%= link_to(post_gym_likes_path(@post_gym), class:"text-dark", method: :delete) do %>
                <i class="fa fa-heart" aria-hidden="true"></i><%= @post_gym.likes.count %>
              <% end %>
            </span>
            <% else %>
            <span>
              <%= link_to(post_gym_likes_path(@post_gym), class:"text-dark", method: :post) do %>
                <i class="fa fa-heart" aria-hidden="true"></i>♡<%= @post_gym.likes.count %>
              <% end %>
            </span>
          <% end %>

          <% if @post_gym.user == current_user %>
            <span> ｜ </span><%= link_to "", post_gym_likes_path(@post_gym),class:"text-dark", method: :delete %>
          <% end %>
        </div>
      </div>

      <div class="comments card-text">
        <h4 class="mt-3 ml-3"><%= @post_gym.comments.count %>件コメント</h4>
        <% @post_gym.comments.each do |comment| %>
          <div class="media border mb-3">
            <div class="media-body ml-4 p-3">
              <p><%= comment.created_at.strftime('%Y/%m/%d') %>|<%= @post_gym.user.name %></p>
              <p><%= comment.comment %></p>
              <% if comment.user == current_user %>
                <%= link_to "削除", post_gym_comment_path(comment.post_gym,comment), method: :delete, class: "btn btn-danger pull-right" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="new-comment card-text">
        <%= form_with(model:[@post_gym, @comment]) do |f| %>
          <div class="form-group ml-3">
            <label for="exampleFormControlTextarea1 ml">コメントする</label>
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
          </div>


          <%= f.submit "送信する", class:"btn btn-info mr-3 float-right" %>
          <% end %>

       <div calss="ml-3">
         <% if @post_gym.user == current_user %>
          <%= link_to "編集", edit_post_gym_path(@post_gym), class:"btn btn-success ml-3"%>
          <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container mt-4">
<div calss="col-12">
<h3>プロフィール編集</h3>
</div>
</div>

<div class="container border bg-light mt-4">
<div class="col-12">
 <%= form_with model: @user, local:true do |f| %>
<div>
  <p class="text-center mt-3"><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class:"mt-3 border rounded-circle"; %></p>
   <p class="text-center">現在のProfileImage</p>
   <p class="text-center"><%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %></p>

  <p class="text-center mt-3">名前 :<%= f.text_field :name, autofocus: true, placeholder:"名前"%></p>
  <p class="text-center mt-4">年齢 :<%= f.text_field :old, autofocus: true, placeholder:"年齢"%></p>
  <p class="text-center mt-4">身長 :<%= f.text_field :height, autofocus: true, placeholder:"身長"%></p>
  <p class="text-center mt-4">体重：<%= f.text_field :body_weight, autofocus: true, placeholder:"体重"%></p>
  <p class="text-center mt-4 mr-4 ">トレーニング歴：<%= f.text_field :experience, autofocus: true, placeholder:"トレーニング歴", class:"mr-5"%></p>

　<p class="text-right"><%= f.submit "変更を保存", class:"btn btn-success" %></p>
</div>


<% end %>

</div>
</div>

app/views/users/show.html.erb
<div class="container mt-4">
<div calss="col-12">
<h3>My page</h3>
</div>
</div>

<div class="container border bg-light mt-4">
<div class="col-12">
<div>

  <p class="text-center mt-4"><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class:"mt-3 border rounded-circle"; %></p>

  <h3 class="text-center mt-4"><%= @user.name %></h3>
  <p class="text-center mt-4">年齢：<%= @user.old %></p>
  <p class="text-center mt-4">身長：<%= @user.height %></p>
  <p class="text-center mt-4">体重：<%= @user.body_weight %></p>
  <p class="text-center mt-4">トレーニング歴：<%= @user.experience %></p>

</div>

 <% if @user.id == current_user.id %>
   <p class="text-right"><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>

</div>
</div>